export const assassin = [
    {
    link:"info-defail.shtml?id=Ahri",
    hero:"九尾妖狐",
    name:"阿狸",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Ahri.png"
    },
    {
    link:"info-defail.shtml?id=Akali",
    hero:"暗影之拳",
    name:"阿卡丽",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Akali.png"
    },
    {
    link:"info-defail.shtml?id=Ekko",
    hero:"时间刺客",
    name:"艾克",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Ekko.png"
    },
    {
    link:"info-defail.shtml?id=Evelynn",
    hero:"痛苦之拥",
    name:"伊芙琳",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Evelynn.png"
    },
    {
    link:"info-defail.shtml?id=Fiora",
    hero:"无双剑姬",
    name:"菲奥娜",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Fiora.png"
    },
    {
    link:"info-defail.shtml?id=Fizz",
    hero:"潮汐海灵",
    name:"菲兹",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Fizz.png"
    },
    {
    link:"info-defail.shtml?id=Irelia",
    hero:"刀锋意志",
    name:"艾瑞莉娅",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Irelia.png"
    },
    {
    link:"info-defail.shtml?id=Jax",
    hero:"武器大师",
    name:"贾克斯",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Jax.png"
    },
    {
    link:"info-defail.shtml?id=Jhin",
    hero:"戏命师",
    name:"烬",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Jhin.png"
    },
    {
    link:"info-defail.shtml?id=Kassadin",
    hero:"虚空行者",
    name:"卡萨丁",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Kassadin.png"
    },
    {
    link:"info-defail.shtml?id=Katarina",
    hero:"不祥之刃",
    name:"卡特琳娜",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Katarina.png"
    },
    {
    link:"info-defail.shtml?id=Kayn",
    hero:"影流之镰",
    name:"凯隐",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Kayn.png"
    },
    {
    link:"info-defail.shtml?id=Khazix",
    hero:"虚空掠夺者",
    name:"卡兹克",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Khazix.png"
    },
    {
    link:"info-defail.shtml?id=Leblanc",
    hero:"诡术妖姬",
    name:"乐芙兰",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Leblanc.png"
    },
    {
    link:"info-defail.shtml?id=LeeSin",
    hero:"盲僧",
    name:"李青",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/LeeSin.png"
    },
    {
    link:"info-defail.shtml?id=Malzahar",
    hero:"虚空先知",
    name:"玛尔扎哈",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Malzahar.png"
    },
    {
    link:"info-defail.shtml?id=MasterYi",
    hero:"无极剑圣",
    name:"易",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/MasterYi.png"
    },
    {
    link:"info-defail.shtml?id=Nidalee",
    hero:"狂野女猎手",
    name:"奈德丽",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Nidalee.png"
    },
    {
    link:"info-defail.shtml?id=Nocturne",
    hero:"永恒梦魇",
    name:"魔腾",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Nocturne.png"
    },
    {
    link:"info-defail.shtml?id=Pantheon",
    hero:"战争之王",
    name:"潘森",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Pantheon.png"
    },
    {
    link:"info-defail.shtml?id=Rengar",
    hero:"傲之追猎者",
    name:"雷恩加尔",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Rengar.png"
    },
    {
    link:"info-defail.shtml?id=Riven",
    hero:"放逐之刃",
    name:"锐雯",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Riven.png"
    },
    {
    link:"info-defail.shtml?id=Shaco",
    hero:"恶魔小丑",
    name:"萨科",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Shaco.png"
    },
    {
    link:"info-defail.shtml?id=Talon",
    hero:"刀锋之影",
    name:"泰隆",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Talon.png"
    },
    {
    link:"info-defail.shtml?id=Teemo",
    hero:"迅捷斥候",
    name:"提莫",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Teemo.png"
    },
    {
    link:"info-defail.shtml?id=Tristana",
    hero:"麦林炮手",
    name:"崔丝塔娜",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Tristana.png"
    },
    {
    link:"info-defail.shtml?id=Tryndamere",
    hero:"蛮族之王",
    name:"泰达米尔",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Tryndamere.png"
    },
    {
    link:"info-defail.shtml?id=Twitch",
    hero:"瘟疫之源",
    name:"图奇",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Twitch.png"
    },
    {
    link:"info-defail.shtml?id=Vayne",
    hero:"暗夜猎手",
    name:"薇恩",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Vayne.png"
    },
    {
    link:"info-defail.shtml?id=Vi",
    hero:"皮城执法官",
    name:"蔚",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Vi.png"
    },
    {
    link:"info-defail.shtml?id=Xerath",
    hero:"远古巫灵",
    name:"泽拉斯",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Xerath.png"
    },
    {
    link:"info-defail.shtml?id=XinZhao",
    hero:"德邦总管",
    name:"赵信",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/XinZhao.png"
    },
    {
    link:"info-defail.shtml?id=Yasuo",
    hero:"疾风剑豪",
    name:"亚索",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Yasuo.png"
    },
    {
    link:"info-defail.shtml?id=Zed",
    hero:"影流之主",
    name:"劫",
    portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Zed.png"
    }]