export const tank = [
{
link:"info-defail.shtml?id=Aatrox",
hero:"暗裔剑魔",
name:"亚托克斯",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Aatrox.png" 
},
{
link:"info-defail.shtml?id=Alistar",
hero:"牛头酋长",
name:"阿利斯塔",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Alistar.png" 
},
{
link:"info-defail.shtml?id=Amumu",
hero:"殇之木乃伊",
name:"阿木木",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Amumu.png" 
},
{
link:"info-defail.shtml?id=Blitzcrank",
hero:"蒸汽机器人",
name:"布里茨",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Blitzcrank.png" 
},
{
link:"info-defail.shtml?id=Braum",
hero:"弗雷尔卓德之心",
name:"布隆",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Braum.png" 
},
{
link:"info-defail.shtml?id=Camille",
hero:"青钢影",
name:"卡蜜尔",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Camille.png" 
},
{
link:"info-defail.shtml?id=Chogath",
hero:"虚空恐惧",
name:"科加斯",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Chogath.png" 
},
{
link:"info-defail.shtml?id=Darius",
hero:"诺克萨斯之手",
name:"德莱厄斯",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Darius.png" 
},
{
link:"info-defail.shtml?id=DrMundo",
hero:"祖安狂人",
name:"蒙多医生",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/DrMundo.png" 
},
{
link:"info-defail.shtml?id=Galio",
hero:"正义巨像",
name:"加里奥",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Galio.png" 
},
{
link:"info-defail.shtml?id=Garen",
hero:"德玛西亚之力",
name:"盖伦",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Garen.png" 
},
{
link:"info-defail.shtml?id=Gnar",
hero:"迷失之牙",
name:"纳尔",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Gnar.png" 
},
{
link:"info-defail.shtml?id=Hecarim",
hero:"战争之影",
name:"赫卡里姆",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Hecarim.png" 
},
{
link:"info-defail.shtml?id=Illaoi",
hero:"海兽祭司",
name:"俄洛伊",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Illaoi.png" 
},
{
link:"info-defail.shtml?id=JarvanIV",
hero:"德玛西亚皇子",
name:"嘉文四世",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/JarvanIV.png" 
},
{
link:"info-defail.shtml?id=Kled",
hero:"暴怒骑士",
name:"克烈",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Kled.png" 
},
{
link:"info-defail.shtml?id=Leona",
hero:"曙光女神",
name:"蕾欧娜",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Leona.png" 
},
{
link:"info-defail.shtml?id=Malphite",
hero:"熔岩巨兽",
name:"墨菲特",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Malphite.png" 
},
{
link:"info-defail.shtml?id=Maokai",
hero:"扭曲树精",
name:"茂凯",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Maokai.png" 
},
{
link:"info-defail.shtml?id=MonkeyKing",
hero:"齐天大圣",
name:"孙悟空",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/MonkeyKing.png" 
},
{
link:"info-defail.shtml?id=Nasus",
hero:"沙漠死神",
name:"内瑟斯",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Nasus.png" 
},
{
link:"info-defail.shtml?id=Nautilus",
hero:"深海泰坦",
name:"诺提勒斯",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Nautilus.png" 
},
{
link:"info-defail.shtml?id=Olaf",
hero:"狂战士",
name:"奥拉夫",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Olaf.png" 
},
{
link:"info-defail.shtml?id=Ornn",
hero:"山隐之焰",
name:"奥恩",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Ornn.png" 
},
{
link:"info-defail.shtml?id=Poppy",
hero:"圣锤之毅",
name:"波比",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Poppy.png" 
},
{
link:"info-defail.shtml?id=Rammus",
hero:"披甲龙龟",
name:"拉莫斯",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Rammus.png" 
},
{
link:"info-defail.shtml?id=Renekton",
hero:"荒漠屠夫",
name:"雷克顿",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Renekton.png" 
},
{
link:"info-defail.shtml?id=Sejuani",
hero:"北地之怒",
name:"瑟庄妮",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Sejuani.png" 
},
{
link:"info-defail.shtml?id=Shen",
hero:"暮光之眼",
name:"慎",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Shen.png" 
},
{
link:"info-defail.shtml?id=Shyvana",
hero:"龙血武姬",
name:"希瓦娜",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Shyvana.png" 
},
{
link:"info-defail.shtml?id=Singed",
hero:"炼金术士",
name:"辛吉德",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Singed.png" 
},
{
link:"info-defail.shtml?id=Sion",
hero:"亡灵战神",
name:"赛恩",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Sion.png" 
},
{
link:"info-defail.shtml?id=Skarner",
hero:"水晶先锋",
name:"斯卡纳",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Skarner.png" 
},
{
link:"info-defail.shtml?id=TahmKench",
hero:"河流之王",
name:"塔姆",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/TahmKench.png" 
},
{
link:"info-defail.shtml?id=Trundle",
hero:"巨魔之王",
name:"特朗德尔",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Trundle.png" 
},
{
link:"info-defail.shtml?id=Udyr",
hero:"兽灵行者",
name:"乌迪尔",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Udyr.png" 
},
{
link:"info-defail.shtml?id=Vladimir",
hero:"猩红收割者",
name:"弗拉基米尔",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Vladimir.png" 
},
{
link:"info-defail.shtml?id=Volibear",
hero:"雷霆咆哮",
name:"沃利贝尔",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Volibear.png" 
},
{
link:"info-defail.shtml?id=Warwick",
hero:"祖安怒兽",
name:"沃里克",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Warwick.png" 
},
{
link:"info-defail.shtml?id=Yorick",
hero:"牧魂人",
name:"约里克",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Yorick.png" 
},
{
link:"info-defail.shtml?id=Zac",
hero:"生化魔人",
name:"扎克",
portrait:"http://ossweb-img.qq.com/images/lol/img/champion/Zac.png"
}]